# !! This file was automatically generated by NEWVERS !!

package Vers;

# for logfiles, etc.
$LCWA_Version =
    "1.0.0 (30-10-1997)";

# interactive 'hello' string to identify us to the user
$LCWA_Hello = 
    "This is LCWA Version 1.0.0 (30-10-1997)";

# a GNU --version output
$LCWA_GNUVersion =
    "LCWA Version 1.0.0";

# a UNIX what(1) id string
$LCWA_WhatID =
    "@(#)LCWA Version 1.0.0 (30-10-1997)";

# a RCS ident(1) id string
$LCWA_RCSIdentID =
    "\$Id: LCWA 1.0.0 30-10-1997 \$";

# a WWW id string
$LCWA_WebID =
    "LCWA/1.0.0";

# a plain id string
$LCWA_PlainID =
    "1.0.0";

package main;
1;
